spring:
  application:
    name: vpn
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

telegram:
  bot:
    vpn:
      name: ${TELEGRAM_BOT_VPN_NAME}
      token: ${TELEGRAM_BOT_VPN_TOKEN}
